apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smartbill-wasc
  namespace: smartbill-wasc
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - smartbill-wasc.com
    - www.smartbill-wasc.com
    secretName: smartbill-wasc-tls
  rules:
  - host: smartbill-wasc.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: smartbill-wasc
            port:
              number: 80
  - host: www.smartbill-wasc.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: smartbill-wasc
            port:
              number: 80
